/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#faf8ff",
        "surface-dim": "#d2d9f4",
        "surface-bright": "#faf8ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "surface-container": "#eaedff",
        "surface-container-high": "#e2e7ff",
        "surface-container-highest": "#dae2fd",
        "on-surface": "#131b2e",
        "on-surface-variant": "#5c403c",
        "inverse-surface": "#283044",
        "inverse-on-surface": "#eef0ff",
        "outline": "#916f6b",
        "outline-variant": "#e6bdb8",
        "surface-tint": "#bf0715",
        "primary": "#b70011",
        "on-primary": "#ffffff",
        "primary-container": "#dc2626",
        "on-primary-container": "#fff6f5",
        "inverse-primary": "#ffb4ab",
        "secondary": "#006c4a",
        "on-secondary": "#ffffff",
        "secondary-container": "#82f5c1",
        "on-secondary-container": "#00714e",
        "tertiary": "#004ed0",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#2d68f0",
        "on-tertiary-container": "#f8f7ff",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffdad6",
        "primary-fixed-dim": "#ffb4ab",
        "on-primary-fixed": "#410002",
        "on-primary-fixed-variant": "#93000b",
        "secondary-fixed": "#85f8c4",
        "secondary-fixed-dim": "#68dba9",
        "on-secondary-fixed": "#002114",
        "on-secondary-fixed-variant": "#005137",
        "tertiary-fixed": "#dbe1ff",
        "tertiary-fixed-dim": "#b4c5ff",
        "on-tertiary-fixed": "#00174b",
        "on-tertiary-fixed-variant": "#003ea8",
        "background": "#faf8ff",
        "on-background": "#131b2e",
        "surface-variant": "#dae2fd",
        "finman": {
          red: "#dc2626",
          darkred: "#b91c1c",
          gold: "#D4AF37",
          darkgold: "#B8860B",
          surface: "#F8FAFC",
        }
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "1.5rem",
        "gutter-desktop": "1.75rem",
        "margin": "1.5rem",
        "margin-desktop": "2.5rem",
        "space-2xs": "0.25rem",
        "space-xs": "0.375rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem"
      },
      fontFamily: {
        sans: ["'Plus Jakarta Sans'", "sans-serif"],
        "display-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "title-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "currency-display": ["'Inter'", "sans-serif"],
        "currency-row": ["'Inter'", "sans-serif"],
        "label-lg": ["'Inter'", "sans-serif"],
        "label-md": ["'Inter'", "sans-serif"],
        "label-sm": ["'Inter'", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["1.75rem", { lineHeight: "2.125rem", letterSpacing: "-0.03em", fontWeight: "800" }],
        "headline-lg": ["1.375rem", { lineHeight: "1.875rem", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["1.125rem", { lineHeight: "1.625rem", letterSpacing: "-0.015em", fontWeight: "700" }],
        "headline-sm": ["1rem", { lineHeight: "1.375rem", letterSpacing: "-0.01em", fontWeight: "600" }],
        "title-md": ["0.9375rem", { lineHeight: "1.375rem", fontWeight: "600" }],
        "body-lg": ["0.9375rem", { lineHeight: "1.375rem", fontWeight: "400" }],
        "body-md": ["0.8125rem", { lineHeight: "1.25rem", fontWeight: "400" }],
        "body-sm": ["0.75rem", { lineHeight: "1rem", fontWeight: "400" }],
        "currency-display": ["1.5rem", { lineHeight: "1.875rem", letterSpacing: "-0.02em", fontWeight: "800" }],
        "currency-row": ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-lg": ["0.8125rem", { lineHeight: "1.125rem", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-md": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-sm": ["0.6875rem", { lineHeight: "0.875rem", letterSpacing: "0.03em", fontWeight: "600" }],
      },
      boxShadow: {
        'modal': '0 25px 60px -15px rgba(0, 0, 0, 0.35)',
        'glow-red': '0 4px 20px -2px rgba(220, 38, 38, 0.35)',
        'glow-emerald': '0 4px 20px -2px rgba(16, 185, 129, 0.35)',
      }
    },
  },
  plugins: [],
}
