/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#f7f9fb",
        "surface-dim": "#d8dadc",
        "surface-bright": "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "surface-container": "#eceef0",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "on-surface": "#191c1e",
        "on-surface-variant": "#5b403e",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
        "outline": "#8f706d",
        "outline-variant": "#e3bebb",
        "surface-tint": "#b81d27",
        "primary": "#b51925",
        "on-primary": "#ffffff",
        "primary-container": "#d8363a",
        "on-primary-container": "#fffbff",
        "inverse-primary": "#ffb3ae",
        "primary-fixed": "#ffdad7",
        "primary-fixed-dim": "#ffb3ae",
        "on-primary-fixed": "#410004",
        "on-primary-fixed-variant": "#930015",
        "secondary": "#0051d5",
        "on-secondary": "#ffffff",
        "secondary-container": "#316bf3",
        "on-secondary-container": "#fefcff",
        "secondary-fixed": "#dbe1ff",
        "secondary-fixed-dim": "#b4c5ff",
        "on-secondary-fixed": "#00174b",
        "on-secondary-fixed-variant": "#003ea8",
        "tertiary": "#006947",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#00855b",
        "on-tertiary-container": "#f5fff6",
        "tertiary-fixed": "#6ffbbe",
        "tertiary-fixed-dim": "#4edea3",
        "on-tertiary-fixed": "#002113",
        "on-tertiary-fixed-variant": "#005236",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "background": "#f7f9fb",
        "on-background": "#191c1e",
        "surface-variant": "#e0e3e5",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "gutter": "1rem",
        "gutter-sm": "0.75rem",
        "margin": "1rem",
        "margin-tablet": "1.5rem",
        "margin-desktop": "2rem",
      },
      fontFamily: {
        sans: ["'Plus Jakarta Sans'", "sans-serif"],
        "display-currency": ["'Plus Jakarta Sans'", "sans-serif"],
        "display-currency-mobile": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "currency-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "currency-sm": ["'Plus Jakarta Sans'", "sans-serif"],
      },
      fontSize: {
        "display-currency": ["36px", { lineHeight: "44px", fontWeight: "800" }],
        "display-currency-mobile": ["30px", { lineHeight: "38px", fontWeight: "800" }],
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "700" }],
        "headline-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
        "currency-md": ["15px", { lineHeight: "20px", fontWeight: "700" }],
        "currency-sm": ["13px", { lineHeight: "18px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
