import type { Transaction } from '../types';

export const DEFAULT_TRANSACTIONS: Transaction[] = [
  {
    id: 101,
    amount: 6000000,
    type: 'INCOME',
    category: {
      id: 7,
      name: 'Lương thưởng',
      type: 'INCOME',
      icon: 'account_balance',
      color: '#006c4a',
      bgColor: '#85f8c4',
    },
    account: {
      id: 1,
      name: 'Vietcombank',
      type: 'BANK',
      currentBalance: 4910000,
      accountNumber: '1023456789',
      bankName: 'Vietcombank',
    },
    date: '2026-09-16',
    time: '09:15',
    note: 'Lương T9 - Chuyển khoản 247',
  },
  {
    id: 102,
    amount: 1000000,
    type: 'EXPENSE',
    category: {
      id: 2,
      name: 'Áo quần',
      type: 'EXPENSE',
      icon: 'checkroom',
      color: '#dc2626',
      bgColor: '#ffdad6',
    },
    account: {
      id: 2,
      name: 'Tiền mặt ví',
      type: 'CASH',
      currentBalance: 1500000,
      accountNumber: 'Ví tiền mặt',
    },
    date: '2026-09-16',
    time: '14:30',
    note: 'Quần Uniqlo Kaki Slim-fit Landmark 81',
  },
  {
    id: 103,
    amount: 90000,
    type: 'EXPENSE',
    category: {
      id: 1,
      name: 'Ăn uống',
      type: 'EXPENSE',
      icon: 'coffee',
      color: '#dc2626',
      bgColor: '#ffdad6',
    },
    account: {
      id: 2,
      name: 'Tiền mặt ví',
      type: 'CASH',
      currentBalance: 1500000,
      accountNumber: 'Ví tiền mặt',
    },
    date: '2026-09-16',
    time: '16:45',
    note: 'Cà phê Highlands gặp đối tác',
  },
  {
    id: 104,
    amount: 110000,
    type: 'EXPENSE',
    category: {
      id: 3,
      name: 'Giao thông',
      type: 'EXPENSE',
      icon: 'local_gas_station',
      color: '#d97706',
      bgColor: '#fef3c7',
    },
    account: {
      id: 2,
      name: 'Tiền mặt ví',
      type: 'CASH',
      currentBalance: 1500000,
      accountNumber: 'Ví tiền mặt',
    },
    date: '2026-09-15',
    time: '08:20',
    note: 'Đổ xăng xe máy Petrolimex',
  },
  {
    id: 105,
    amount: 2500000,
    type: 'INCOME',
    category: {
      id: 8,
      name: 'Thưởng & Đầu tư',
      type: 'INCOME',
      icon: 'trending_up',
      color: '#006c4a',
      bgColor: '#85f8c4',
    },
    account: {
      id: 1,
      name: 'Vietcombank',
      type: 'BANK',
      currentBalance: 4910000,
      accountNumber: '1023456789',
      bankName: 'Vietcombank',
    },
    date: '2026-09-14',
    time: '17:00',
    note: 'Thưởng KPI Quý 3',
  },
];
